Day 8 - Big grid of trees, which are visible?

Only care about 2D neighbours (LRUD) ALL THE WAY TO THE EDGE (not just next to!) ... and all outer edge are visible!

In [179]:
import numpy as np

In [180]:
input = []

with open('day8-example.txt', 'r') as f:
    for line in f.readlines():
        input.append(line.rstrip())

grid = [[*row] for row in input]

grid = np.array(grid).astype(int)
grid[-1][0]

# format grid [y][x]

3

In [181]:
False in list(9 > np.array([1,2,3,4,5,6]))
arrr = np.array([[1,2,3],[3,4,5],[6,7,8]]) 
arrr


array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [182]:
arrr[:1,1]

array([2])

In [183]:
arrr = np.array([[1,2,3],[3,4,5],[6,7,8]]) 
arr_cmp = 3 >= arrr[:,:2]
if not arr_cmp.all():
    print('not visible')
else:
    print('visible')

not visible


In [184]:
# Have to check all the way to the edge!

def generate_visible_grid(grid_array):
    length = len(grid_array)
    visibile_grid = np.zeros((length,length), dtype=int)
    for y in range(length):
        for x in range(length):
            if (x == 0) or (y == 0) or (x == length-1) or (y == length-1): # we're on the edge
                visibile_grid[y][x] = 1
            else:
                comparisons_x_LEFT = grid_array[y][x] > grid_array[y,:x] # compare to that specific row but all to the left
                comparisons_x_RIGHT = grid_array[y][x] > grid_array[y,x+1:] # compare to that specific row but all to the right
                comparisons_y_LEFT = grid_array[y][x] > grid_array[y+1:,x] # compare to that specific column but all to the left
                comparisons_y_RIGHT = grid_array[y][x] > grid_array[:y,x] # compare to that specific column but all to the right
                if comparisons_x_LEFT.all() or comparisons_y_LEFT.all() or comparisons_x_RIGHT.all() or comparisons_y_RIGHT.all():
                    # if there's just one tree it wasn't bigger than in the row, then it is not visible
                    visibile_grid[y][x] = 1
                else:
                    visibile_grid[y][x] = 0
    
    return visibile_grid

In [185]:
visible_grid = generate_visible_grid(grid)

visible_grid

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 0, 1],
       [1, 1, 0, 1, 1],
       [1, 0, 1, 0, 1],
       [1, 1, 1, 1, 1]])

In [186]:
visible_grid.sum()

21

Part 2: Scenic score (looking at distances the nearest blocker tree is away)

In [266]:
def generate_scenic_grid(grid_array):
    length = len(grid_array)
    scenic = np.zeros((length,length), dtype=int)
    for y in range(length):
        for x in range(length):
            if (x == 0): 
                distL = 0
            else:
                distL = 0
                for i in range(x):
                    if grid_array[y,x-i-1] < grid_array[y,x]:
                        distL +=1
                    else:
                        if distL == 0: distL = 1
                        break

            if (y == 0): 
                distU = 0
            else:
                distU = 0
                for i in range(length-y-1):
                    if grid_array[y+i+1,x] < grid_array[y,x]:   ## WE ARE DOUBLE COUNTING FIRST ONE
                        distU +=1
                    else:
                        if distU == 0: distU = 1
                        break

            if (x == length-1):
                distR = 0
            else:
                distR = 0 
                for i in range(length-x-1):
                    if grid_array[y,x+i+1] < grid_array[y,x]:
                        distR +=1
                    else:
                        if distR == 0: distR = 1
                        break

            if (y == length-1): 
                distD = 0
            else:
                distD = 0
                for i in range(y):
                    if grid_array[y-i-1,x] < grid_array[y,x]:
                        distD +=1
                    else:
                        if distD == 0: distD = 1
                        break            

            scenic_score = distU*distD*distL*distR
            scenic[y,x] = scenic_score

    return scenic

In [262]:
scenic = generate_scenic_grid(grid)

In [240]:
grid

array([[3, 0, 3, 7, 3],
       [2, 5, 5, 1, 2],
       [6, 5, 3, 3, 2],
       [3, 3, 5, 4, 9],
       [3, 5, 3, 9, 0]])